// Generated by gencpp from file rcnn_pkg/graymask.msg
// DO NOT EDIT!


#ifndef RCNN_PKG_MESSAGE_GRAYMASK_H
#define RCNN_PKG_MESSAGE_GRAYMASK_H

#include <ros/service_traits.h>


#include <rcnn_pkg/graymaskRequest.h>
#include <rcnn_pkg/graymaskResponse.h>


namespace rcnn_pkg
{

struct graymask
{

typedef graymaskRequest Request;
typedef graymaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct graymask
} // namespace rcnn_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rcnn_pkg::graymask > {
  static const char* value()
  {
    return "d5d593fffd3f0c2cae51095bbf8f752b";
  }

  static const char* value(const ::rcnn_pkg::graymask&) { return value(); }
};

template<>
struct DataType< ::rcnn_pkg::graymask > {
  static const char* value()
  {
    return "rcnn_pkg/graymask";
  }

  static const char* value(const ::rcnn_pkg::graymask&) { return value(); }
};


// service_traits::MD5Sum< ::rcnn_pkg::graymaskRequest> should match
// service_traits::MD5Sum< ::rcnn_pkg::graymask >
template<>
struct MD5Sum< ::rcnn_pkg::graymaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rcnn_pkg::graymask >::value();
  }
  static const char* value(const ::rcnn_pkg::graymaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rcnn_pkg::graymaskRequest> should match
// service_traits::DataType< ::rcnn_pkg::graymask >
template<>
struct DataType< ::rcnn_pkg::graymaskRequest>
{
  static const char* value()
  {
    return DataType< ::rcnn_pkg::graymask >::value();
  }
  static const char* value(const ::rcnn_pkg::graymaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rcnn_pkg::graymaskResponse> should match
// service_traits::MD5Sum< ::rcnn_pkg::graymask >
template<>
struct MD5Sum< ::rcnn_pkg::graymaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rcnn_pkg::graymask >::value();
  }
  static const char* value(const ::rcnn_pkg::graymaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rcnn_pkg::graymaskResponse> should match
// service_traits::DataType< ::rcnn_pkg::graymask >
template<>
struct DataType< ::rcnn_pkg::graymaskResponse>
{
  static const char* value()
  {
    return DataType< ::rcnn_pkg::graymask >::value();
  }
  static const char* value(const ::rcnn_pkg::graymaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCNN_PKG_MESSAGE_GRAYMASK_H
