// Generated by gencpp from file rcnn_pkg/graymaskResponse.msg
// DO NOT EDIT!


#ifndef RCNN_PKG_MESSAGE_GRAYMASKRESPONSE_H
#define RCNN_PKG_MESSAGE_GRAYMASKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcnn_pkg
{
template <class ContainerAllocator>
struct graymaskResponse_
{
  typedef graymaskResponse_<ContainerAllocator> Type;

  graymaskResponse_()
    : result()  {
    }
  graymaskResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct graymaskResponse_

typedef ::rcnn_pkg::graymaskResponse_<std::allocator<void> > graymaskResponse;

typedef boost::shared_ptr< ::rcnn_pkg::graymaskResponse > graymaskResponsePtr;
typedef boost::shared_ptr< ::rcnn_pkg::graymaskResponse const> graymaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcnn_pkg::graymaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rcnn_pkg::graymaskResponse_<ContainerAllocator1> & lhs, const ::rcnn_pkg::graymaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rcnn_pkg::graymaskResponse_<ContainerAllocator1> & lhs, const ::rcnn_pkg::graymaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rcnn_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::rcnn_pkg::graymaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcnn_pkg/graymaskResponse";
  }

  static const char* value(const ::rcnn_pkg::graymaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::rcnn_pkg::graymaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graymaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcnn_pkg::graymaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcnn_pkg::graymaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCNN_PKG_MESSAGE_GRAYMASKRESPONSE_H
