// Generated by gencpp from file rcnn_pkg/graymaskRequest.msg
// DO NOT EDIT!


#ifndef RCNN_PKG_MESSAGE_GRAYMASKREQUEST_H
#define RCNN_PKG_MESSAGE_GRAYMASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcnn_pkg
{
template <class ContainerAllocator>
struct graymaskRequest_
{
  typedef graymaskRequest_<ContainerAllocator> Type;

  graymaskRequest_()
    : obj_id()  {
    }
  graymaskRequest_(const ContainerAllocator& _alloc)
    : obj_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _obj_id_type;
  _obj_id_type obj_id;





  typedef boost::shared_ptr< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct graymaskRequest_

typedef ::rcnn_pkg::graymaskRequest_<std::allocator<void> > graymaskRequest;

typedef boost::shared_ptr< ::rcnn_pkg::graymaskRequest > graymaskRequestPtr;
typedef boost::shared_ptr< ::rcnn_pkg::graymaskRequest const> graymaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcnn_pkg::graymaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rcnn_pkg::graymaskRequest_<ContainerAllocator1> & lhs, const ::rcnn_pkg::graymaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obj_id == rhs.obj_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rcnn_pkg::graymaskRequest_<ContainerAllocator1> & lhs, const ::rcnn_pkg::graymaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rcnn_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92426bd0785e0b4655ae981c76b9de6b";
  }

  static const char* value(const ::rcnn_pkg::graymaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92426bd0785e0b46ULL;
  static const uint64_t static_value2 = 0x55ae981c76b9de6bULL;
};

template<class ContainerAllocator>
struct DataType< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcnn_pkg/graymaskRequest";
  }

  static const char* value(const ::rcnn_pkg::graymaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obj_id\n"
;
  }

  static const char* value(const ::rcnn_pkg::graymaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graymaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcnn_pkg::graymaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcnn_pkg::graymaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "obj_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.obj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCNN_PKG_MESSAGE_GRAYMASKREQUEST_H
